version: '3.8'
services:
  postgres:
    container_name: postgres-carimakan-drizzle
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env

  pgadmin:
    container_name: pgadmin-carimakan-drizzle
    image: dpage/pgadmin4:latest
    ports:
      - '8080:80'
    env_file:
      - docker.env
    depends_on:
      - postgres

volumes:
  postgres_data:
